import type {
  Weakness,
  TemporalDataPoint,
  KnowledgeNode,
  KnowledgeEdge,
  LearnerProfile,
  DomainSummary,
  InterventionStep,
} from "@/types/weakness";

export const learnerProfile: LearnerProfile = {
  id: "learner_001",
  name: "Alex Chen",
  overallMastery: 0.42,
  totalWeaknesses: 17,
  criticalCount: 7,
  improvingCount: 3,
  studyStreak: 12,
  lastActive: "2026-03-21T14:30:00",
};

export const weaknesses: Weakness[] = [
  {
    rank: 1,
    topic_id: "linear_eq",
    topic_name: "Linear Equations",
    domain: "Mathematics",
    severity_score: 0.871,
    p_mastery: 0.095,
    confidence: 0.913,
    mastery_velocity: -0.2597,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.095, threshold: 0.5, description: "Bayesian Knowledge Tracing estimates only 9.5% mastery probability (threshold: 50%)" },
      { signal: "Test Accuracy", value: 0.35, threshold: 0.5, description: "Average test accuracy is 35.0% across 4 attempts" },
      { signal: "Practice Accuracy", value: 0.272, threshold: 0.5, description: "Practice accuracy is 27.2% across 5 sessions" },
      { signal: "Low Completion", value: 0.524, threshold: 0.65, description: "Average session completion is only 52.4%" },
      { signal: "Negative Mastery Trend", value: -0.2597, threshold: -0.03, description: "Mastery is declining over time (velocity: -0.2597)" },
    ],
    root_causes: ["Algebra Basics (P(mastery)=9.5%)"],
    downstream_impact: ["Quadratic Equations", "Work & Energy", "Newton's Laws of Motion", "Trigonometry", "Introduction to Calculus", "Functions & Graphs", "Waves & Oscillations", "Kinematics"],
    reasoning: "[Prerequisite Cascade Effect] Linear Equations (Mathematics)\n\nWHY this is a weakness:\n  - Bayesian Knowledge Tracing estimates only 9.5% mastery probability\n  - Average test accuracy is 35.0% across 4 attempts\n  - Practice accuracy is 27.2% across 5 sessions\n\nROOT CAUSE ANALYSIS:\n  This weakness likely stems from gaps in prerequisite topics:\n  -> Algebra Basics (P(mastery)=9.5%)\n\nTREND: Performance is DECLINING (velocity: -0.2597).\n  This requires immediate attention as the gap is widening.\n\nDOWNSTREAM IMPACT (8 topics affected):\n  - Quadratic Equations\n  - Trigonometry\n  - Functions & Graphs\n  - Introduction to Calculus\n  - and 4 more Physics topics",
  },
  {
    rank: 2,
    topic_id: "algebra_basics",
    topic_name: "Algebra Basics",
    domain: "Mathematics",
    severity_score: 0.821,
    p_mastery: 0.095,
    confidence: 0.999,
    mastery_velocity: -0.1088,
    weakness_type: "declining",
    evidence: [
      { signal: "BKT Mastery", value: 0.095, threshold: 0.5, description: "Bayesian Knowledge Tracing estimates only 9.5% mastery probability" },
      { signal: "Test Accuracy", value: 0.20, threshold: 0.5, description: "Average test accuracy is 20.0% across 1 attempt" },
      { signal: "Practice Accuracy", value: 0.231, threshold: 0.5, description: "Practice accuracy is 23.1% across 2 sessions" },
      { signal: "Low Completion", value: 0.51, threshold: 0.65, description: "Average session completion is only 51.0%" },
      { signal: "Negative Mastery Trend", value: -0.1088, threshold: -0.03, description: "Mastery is declining over time" },
    ],
    root_causes: [],
    downstream_impact: ["Quadratic Equations", "Work & Energy", "Newton's Laws of Motion", "Trigonometry", "Probability", "Statistics", "Linear Equations", "Functions & Graphs", "Introduction to Calculus", "Kinematics", "Waves & Oscillations"],
    reasoning: "[Declining Performance] Algebra Basics (Mathematics)\n\nWHY this is a weakness:\n  - BKT estimates only 9.5% mastery probability\n  - Test accuracy is 20.0% across 1 attempt\n  - Practice accuracy is 23.1%\n\nTREND: Performance is DECLINING (velocity: -0.1088).\n  This requires immediate attention as the gap is widening.\n\nDOWNSTREAM IMPACT (11 topics affected):\n  This is the MOST impactful weakness - it cascades into 11 downstream topics across Mathematics and Physics.",
  },
  {
    rank: 3,
    topic_id: "control_flow",
    topic_name: "Control Flow",
    domain: "Programming",
    severity_score: 0.760,
    p_mastery: 0.133,
    confidence: 0.939,
    mastery_velocity: -0.1668,
    weakness_type: "declining",
    evidence: [
      { signal: "BKT Mastery", value: 0.133, threshold: 0.5, description: "BKT estimates only 13.3% mastery probability" },
      { signal: "Test Accuracy", value: 0.153, threshold: 0.5, description: "Average test accuracy is 15.3% across 6 attempts" },
      { signal: "Practice Accuracy", value: 0.091, threshold: 0.5, description: "Practice accuracy is 9.1% across 6 sessions" },
      { signal: "Hint Dependency", value: 0.70, threshold: 0.4, description: "High hint usage (0.70 hints/exercise)" },
      { signal: "Low Completion", value: 0.597, threshold: 0.65, description: "Average session completion is only 59.7%" },
    ],
    root_causes: [],
    downstream_impact: ["Recursion", "Data Structures", "Functions & Scope", "Algorithms & Complexity"],
    reasoning: "[Declining Performance] Control Flow (Programming)\n\nWHY this is a weakness:\n  - BKT estimates only 13.3% mastery probability\n  - Test accuracy is 15.3% across 6 attempts\n  - High hint dependency (0.70 hints/exercise)\n\nTREND: Performance is DECLINING (velocity: -0.1668).\n  Immediate intervention needed.\n\nDOWNSTREAM IMPACT: 4 Programming topics blocked.",
  },
  {
    rank: 4,
    topic_id: "functions",
    topic_name: "Functions & Graphs",
    domain: "Mathematics",
    severity_score: 0.752,
    p_mastery: 0.095,
    confidence: 1.0,
    mastery_velocity: -0.0205,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.095, threshold: 0.5, description: "BKT estimates only 9.5% mastery probability" },
      { signal: "Test Accuracy", value: 0.0, threshold: 0.5, description: "Average test accuracy is 0.0% across 1 attempt" },
      { signal: "Practice Accuracy", value: 0.118, threshold: 0.5, description: "Practice accuracy is 11.8% across 4 sessions" },
      { signal: "Hint Dependency", value: 0.59, threshold: 0.4, description: "High hint usage (0.59 hints/exercise)" },
    ],
    root_causes: ["Linear Equations (P(mastery)=9.5%)", "Algebra Basics (P(mastery)=9.5%)"],
    downstream_impact: ["Waves & Oscillations", "Work & Energy", "Introduction to Calculus", "Trigonometry"],
    reasoning: "[Prerequisite Cascade Effect] Functions & Graphs (Mathematics)\n\nROOT CAUSE:\n  -> Linear Equations (9.5% mastery)\n  -> Algebra Basics (9.5% mastery)\n\nFix the prerequisites first for cascading improvement.",
  },
  {
    rank: 5,
    topic_id: "kinematics",
    topic_name: "Kinematics",
    domain: "Physics",
    severity_score: 0.729,
    p_mastery: 0.086,
    confidence: 0.978,
    mastery_velocity: -0.0363,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.086, threshold: 0.5, description: "BKT estimates only 8.6% mastery" },
      { signal: "Test Accuracy", value: 0.183, threshold: 0.5, description: "Test accuracy 18.3% across 2 attempts" },
      { signal: "Declining Accuracy", value: -0.1667, threshold: -0.02, description: "Test accuracy is declining" },
      { signal: "Hint Dependency", value: 0.50, threshold: 0.4, description: "High hint usage" },
    ],
    root_causes: ["Algebra Basics (P(mastery)=9.5%)", "Linear Equations (P(mastery)=9.5%)"],
    downstream_impact: ["Waves & Oscillations", "Work & Energy", "Newton's Laws of Motion"],
    reasoning: "[Prerequisite Cascade] Kinematics (Physics)\n\nThis Physics weakness traces back to Math foundations.\n\nROOT CAUSE: Algebra Basics → Linear Equations → Kinematics\n\nThe learner cannot solve kinematics problems because they lack the algebraic manipulation skills required.",
  },
  {
    rank: 6,
    topic_id: "trigonometry",
    topic_name: "Trigonometry",
    domain: "Mathematics",
    severity_score: 0.721,
    p_mastery: 0.095,
    confidence: 0.981,
    mastery_velocity: -0.005,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.095, threshold: 0.5, description: "BKT estimates 9.5% mastery" },
      { signal: "Test Accuracy", value: 0.117, threshold: 0.5, description: "Test accuracy 11.7% across 4 attempts" },
      { signal: "Practice Accuracy", value: 0.174, threshold: 0.5, description: "Practice accuracy 17.4%" },
    ],
    root_causes: ["Functions & Graphs (9.5%)", "Linear Equations (9.5%)", "Algebra Basics (9.5%)"],
    downstream_impact: ["Waves & Oscillations", "Work & Energy", "Introduction to Calculus"],
    reasoning: "[Prerequisite Cascade] Trigonometry\n\nDeep cascade: Algebra → Linear Eq → Functions → Trigonometry\nAll upstream topics are weak, creating compounding failure.",
  },
  {
    rank: 7,
    topic_id: "data_structures",
    topic_name: "Data Structures",
    domain: "Programming",
    severity_score: 0.719,
    p_mastery: 0.133,
    confidence: 0.899,
    mastery_velocity: -0.073,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.133, threshold: 0.5, description: "BKT estimates 13.3% mastery" },
      { signal: "Test Accuracy", value: 0.14, threshold: 0.5, description: "Test accuracy 14.0%" },
      { signal: "Skip Rate", value: 0.18, threshold: 0.15, description: "High skip rate suggests avoidance" },
    ],
    root_causes: ["Functions & Scope (13.2%)", "Control Flow (13.3%)"],
    downstream_impact: ["Recursion", "Algorithms & Complexity"],
    reasoning: "[Prerequisite Cascade] Data Structures (Programming)\n\nROOT CAUSE: Control Flow → Functions → Data Structures\nHigh skip rate (18%) suggests avoidance behavior.",
  },
  {
    rank: 8,
    topic_id: "newtons_laws",
    topic_name: "Newton's Laws",
    domain: "Physics",
    severity_score: 0.674,
    p_mastery: 0.086,
    confidence: 0.978,
    mastery_velocity: -0.005,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.086, threshold: 0.5, description: "BKT estimates 8.6% mastery" },
      { signal: "Test Accuracy", value: 0.193, threshold: 0.5, description: "Test accuracy 19.3%" },
      { signal: "Skip Rate", value: 0.293, threshold: 0.15, description: "Very high skip rate (29.3%)" },
      { signal: "Hint Dependency", value: 1.0, threshold: 0.4, description: "Extreme hint usage (1.0/exercise)" },
    ],
    root_causes: ["Kinematics (8.6%)", "Algebra Basics (9.5%)", "Linear Equations (9.5%)"],
    downstream_impact: ["Waves & Oscillations", "Work & Energy"],
    reasoning: "[Prerequisite Cascade] Newton's Laws\n\nExtreme hint dependency (1.0 per exercise) and 29.3% skip rate indicate severe comprehension gap rooted in prerequisite weaknesses.",
  },
  {
    rank: 9,
    topic_id: "probability",
    topic_name: "Probability",
    domain: "Mathematics",
    severity_score: 0.653,
    p_mastery: 0.097,
    confidence: 0.966,
    mastery_velocity: -0.0883,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.097, threshold: 0.5, description: "BKT estimates 9.7% mastery" },
      { signal: "Test Accuracy", value: 0.212, threshold: 0.5, description: "Test accuracy 21.2%" },
      { signal: "Hint Dependency", value: 0.65, threshold: 0.4, description: "High hint usage" },
    ],
    root_causes: ["Algebra Basics (9.5%)"],
    downstream_impact: ["Statistics"],
    reasoning: "[Prerequisite Cascade] Probability\n\nROOT CAUSE: Algebra Basics weakness blocks probabilistic reasoning.\nDeclining at -0.0883/observation.",
  },
  {
    rank: 10,
    topic_id: "algorithms",
    topic_name: "Algorithms & Complexity",
    domain: "Programming",
    severity_score: 0.625,
    p_mastery: 0.132,
    confidence: 0.934,
    mastery_velocity: -0.0434,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.132, threshold: 0.5, description: "BKT estimates 13.2% mastery" },
      { signal: "Test Accuracy", value: 0.10, threshold: 0.5, description: "Test accuracy 10.0%" },
      { signal: "Skip Rate", value: 0.20, threshold: 0.15, description: "High skip rate" },
    ],
    root_causes: ["Recursion (13.2%)", "Functions & Scope (13.2%)", "Control Flow (13.3%)", "Data Structures (13.3%)"],
    downstream_impact: [],
    reasoning: "[Prerequisite Cascade] Algorithms & Complexity\n\nFull chain: Control Flow → Functions → Data Structures → Recursion → Algorithms\nEvery prerequisite is weak — this is the deepest cascade in Programming.",
  },
  {
    rank: 11,
    topic_id: "recursion",
    topic_name: "Recursion",
    domain: "Programming",
    severity_score: 0.610,
    p_mastery: 0.132,
    confidence: 0.998,
    mastery_velocity: 0.0779,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.132, threshold: 0.5, description: "BKT estimates 13.2% mastery" },
      { signal: "Test Accuracy", value: 0.112, threshold: 0.5, description: "Test accuracy 11.2%" },
      { signal: "Skip Rate", value: 0.225, threshold: 0.15, description: "22.5% skip rate" },
    ],
    root_causes: ["Functions & Scope (13.2%)", "Control Flow (13.3%)", "Data Structures (13.3%)"],
    downstream_impact: ["Algorithms & Complexity"],
    reasoning: "[Prerequisite Cascade] Recursion\n\nSome improvement detected (velocity: +0.0779) but still far from mastery. Prerequisite gaps in Functions & Scope and Data Structures are the primary blockers.",
  },
  {
    rank: 12,
    topic_id: "waves",
    topic_name: "Waves & Oscillations",
    domain: "Physics",
    severity_score: 0.610,
    p_mastery: 0.080,
    confidence: 0.978,
    mastery_velocity: -0.0227,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.080, threshold: 0.5, description: "BKT estimates 8.0% mastery" },
      { signal: "Test Accuracy", value: 0.167, threshold: 0.5, description: "Test accuracy 16.7%" },
      { signal: "Practice Accuracy", value: 0.109, threshold: 0.5, description: "Practice accuracy 10.9%" },
    ],
    root_causes: ["Trigonometry (9.5%)", "Newton's Laws (8.6%)", "Kinematics (8.6%)"],
    downstream_impact: [],
    reasoning: "[Prerequisite Cascade] Waves & Oscillations\n\nDeepest Physics cascade: Multiple Math and Physics prerequisites are all weak. This topic has the lowest mastery (8.0%) in the entire profile.",
  },
  {
    rank: 13,
    topic_id: "calculus_intro",
    topic_name: "Intro to Calculus",
    domain: "Mathematics",
    severity_score: 0.591,
    p_mastery: 0.096,
    confidence: 0.981,
    mastery_velocity: 0.0504,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.096, threshold: 0.5, description: "BKT estimates 9.6% mastery" },
      { signal: "Test Accuracy", value: 0.10, threshold: 0.5, description: "Test accuracy 10.0%" },
    ],
    root_causes: ["Functions & Graphs (9.5%)", "Linear Equations (9.5%)", "Trigonometry (9.5%)"],
    downstream_impact: ["Work & Energy"],
    reasoning: "[Prerequisite Cascade] Introduction to Calculus\n\nSlightly improving (+0.0504) but all prerequisites are weak. Cannot master calculus without solid algebra and trig foundations.",
  },
  {
    rank: 14,
    topic_id: "functions_prog",
    topic_name: "Functions & Scope",
    domain: "Programming",
    severity_score: 0.591,
    p_mastery: 0.132,
    confidence: 0.600,
    mastery_velocity: -0.0273,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.132, threshold: 0.5, description: "BKT estimates 13.2% mastery" },
      { signal: "Practice Accuracy", value: 0.387, threshold: 0.5, description: "Practice accuracy 38.7%" },
      { signal: "Low Completion", value: 0.477, threshold: 0.65, description: "Completion only 47.7%" },
    ],
    root_causes: ["Control Flow (13.3%)"],
    downstream_impact: ["Recursion", "Data Structures", "Algorithms & Complexity"],
    reasoning: "[Prerequisite Cascade] Functions & Scope\n\nROOT CAUSE: Control Flow weakness cascades here.\nDeclining and blocking 3 downstream topics.",
  },
  {
    rank: 15,
    topic_id: "statistics",
    topic_name: "Statistics",
    domain: "Mathematics",
    severity_score: 0.590,
    p_mastery: 0.095,
    confidence: 0.395,
    mastery_velocity: -0.0654,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.095, threshold: 0.5, description: "BKT estimates 9.5% mastery" },
      { signal: "Practice Accuracy", value: 0.30, threshold: 0.5, description: "Practice accuracy 30.0%" },
    ],
    root_causes: ["Probability (9.7%)", "Algebra Basics (9.5%)"],
    downstream_impact: [],
    reasoning: "[Prerequisite Cascade] Statistics\n\nROOT CAUSE: Probability and Algebra weaknesses prevent statistical reasoning.\nLow confidence (0.395) due to limited observations.",
  },
  {
    rank: 16,
    topic_id: "work_energy",
    topic_name: "Work & Energy",
    domain: "Physics",
    severity_score: 0.576,
    p_mastery: 0.080,
    confidence: 1.0,
    mastery_velocity: -0.005,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.080, threshold: 0.5, description: "BKT estimates 8.0% mastery" },
      { signal: "Test Accuracy", value: 0.144, threshold: 0.5, description: "Test accuracy 14.4%" },
      { signal: "Skip Rate", value: 0.20, threshold: 0.15, description: "20% skip rate" },
      { signal: "Practice Accuracy", value: 0.047, threshold: 0.5, description: "Practice accuracy only 4.7%" },
    ],
    root_causes: ["Newton's Laws (8.6%)", "Kinematics (8.6%)", "Intro to Calculus (9.6%)"],
    downstream_impact: [],
    reasoning: "[Prerequisite Cascade] Work & Energy\n\nDeepest cascade in Physics. Practice accuracy of 4.7% is the lowest across all topics. Multiple prerequisite chains converge here.",
  },
  {
    rank: 17,
    topic_id: "quadratic_eq",
    topic_name: "Quadratic Equations",
    domain: "Mathematics",
    severity_score: 0.521,
    p_mastery: 0.095,
    confidence: 1.0,
    mastery_velocity: -0.002,
    weakness_type: "prerequisite_cascade",
    evidence: [
      { signal: "BKT Mastery", value: 0.095, threshold: 0.5, description: "BKT estimates 9.5% mastery" },
      { signal: "Test Accuracy", value: 0.20, threshold: 0.5, description: "Test accuracy 20.0%" },
      { signal: "Skip Rate", value: 0.367, threshold: 0.15, description: "Very high skip rate (36.7%)" },
    ],
    root_causes: ["Linear Equations (9.5%)", "Algebra Basics (9.5%)"],
    downstream_impact: [],
    reasoning: "[Prerequisite Cascade] Quadratic Equations\n\n36.7% skip rate — highest in the entire profile. The learner is avoiding these problems entirely, likely due to Algebra and Linear Equation gaps.",
  },
];

export const temporalData: TemporalDataPoint[] = Array.from({ length: 35 }, (_, i) => {
  const date = new Date(2026, 0, 15 + i);
  const dayStr = date.toISOString().split("T")[0];
  const t = i / 34;
  const isPredicted = i > 29;

  const noise = () => (Math.random() - 0.5) * 0.08;

  return {
    date: dayStr,
    test_accuracy: Math.max(0, Math.min(1, 0.38 - 0.06 * t + noise() + (isPredicted ? -0.02 * (i - 29) : 0))),
    practice_accuracy: Math.max(0, Math.min(1, 0.32 - 0.04 * t + noise() + (isPredicted ? -0.015 * (i - 29) : 0))),
    engagement_index: Math.max(0, Math.min(1, 0.55 + 0.1 * Math.sin(t * 6) + noise())),
    predicted: isPredicted,
  };
});

export const knowledgeNodes: KnowledgeNode[] = [
  // Mathematics
  { id: "math_basics", label: "Arithmetic", domain: "Mathematics", mastery: 0.82, difficulty: 0.1, isWeak: false, severityScore: 0 },
  { id: "fractions", label: "Fractions", domain: "Mathematics", mastery: 0.75, difficulty: 0.2, isWeak: false, severityScore: 0 },
  { id: "algebra_basics", label: "Algebra Basics", domain: "Mathematics", mastery: 0.095, difficulty: 0.3, isWeak: true, severityScore: 0.821 },
  { id: "linear_eq", label: "Linear Equations", domain: "Mathematics", mastery: 0.095, difficulty: 0.4, isWeak: true, severityScore: 0.871 },
  { id: "quadratic_eq", label: "Quadratic Eq.", domain: "Mathematics", mastery: 0.095, difficulty: 0.5, isWeak: true, severityScore: 0.521 },
  { id: "functions", label: "Functions", domain: "Mathematics", mastery: 0.095, difficulty: 0.5, isWeak: true, severityScore: 0.752 },
  { id: "trigonometry", label: "Trigonometry", domain: "Mathematics", mastery: 0.095, difficulty: 0.6, isWeak: true, severityScore: 0.721 },
  { id: "calculus_intro", label: "Calculus", domain: "Mathematics", mastery: 0.096, difficulty: 0.7, isWeak: true, severityScore: 0.591 },
  { id: "probability", label: "Probability", domain: "Mathematics", mastery: 0.097, difficulty: 0.5, isWeak: true, severityScore: 0.653 },
  { id: "statistics", label: "Statistics", domain: "Mathematics", mastery: 0.095, difficulty: 0.5, isWeak: true, severityScore: 0.590 },
  // Physics
  { id: "physics_units", label: "Units & Measurements", domain: "Physics", mastery: 0.88, difficulty: 0.15, isWeak: false, severityScore: 0 },
  { id: "kinematics", label: "Kinematics", domain: "Physics", mastery: 0.086, difficulty: 0.4, isWeak: true, severityScore: 0.729 },
  { id: "newtons_laws", label: "Newton's Laws", domain: "Physics", mastery: 0.086, difficulty: 0.5, isWeak: true, severityScore: 0.674 },
  { id: "work_energy", label: "Work & Energy", domain: "Physics", mastery: 0.080, difficulty: 0.55, isWeak: true, severityScore: 0.576 },
  { id: "waves", label: "Waves", domain: "Physics", mastery: 0.080, difficulty: 0.6, isWeak: true, severityScore: 0.610 },
  // Programming
  { id: "prog_basics", label: "Programming Basics", domain: "Programming", mastery: 0.85, difficulty: 0.15, isWeak: false, severityScore: 0 },
  { id: "variables_types", label: "Variables & Types", domain: "Programming", mastery: 0.78, difficulty: 0.2, isWeak: false, severityScore: 0 },
  { id: "control_flow", label: "Control Flow", domain: "Programming", mastery: 0.133, difficulty: 0.3, isWeak: true, severityScore: 0.760 },
  { id: "functions_prog", label: "Functions & Scope", domain: "Programming", mastery: 0.132, difficulty: 0.4, isWeak: true, severityScore: 0.591 },
  { id: "data_structures", label: "Data Structures", domain: "Programming", mastery: 0.133, difficulty: 0.5, isWeak: true, severityScore: 0.719 },
  { id: "recursion", label: "Recursion", domain: "Programming", mastery: 0.132, difficulty: 0.6, isWeak: true, severityScore: 0.610 },
  { id: "algorithms", label: "Algorithms", domain: "Programming", mastery: 0.132, difficulty: 0.7, isWeak: true, severityScore: 0.625 },
];

export const knowledgeEdges: KnowledgeEdge[] = [
  { source: "math_basics", target: "fractions", weight: 1.0 },
  { source: "math_basics", target: "algebra_basics", weight: 1.0 },
  { source: "fractions", target: "algebra_basics", weight: 0.8 },
  { source: "algebra_basics", target: "linear_eq", weight: 1.0 },
  { source: "linear_eq", target: "quadratic_eq", weight: 1.0 },
  { source: "algebra_basics", target: "quadratic_eq", weight: 0.7 },
  { source: "linear_eq", target: "functions", weight: 1.0 },
  { source: "functions", target: "trigonometry", weight: 0.9 },
  { source: "algebra_basics", target: "trigonometry", weight: 0.6 },
  { source: "functions", target: "calculus_intro", weight: 1.0 },
  { source: "trigonometry", target: "calculus_intro", weight: 0.8 },
  { source: "fractions", target: "probability", weight: 0.7 },
  { source: "algebra_basics", target: "probability", weight: 0.8 },
  { source: "probability", target: "statistics", weight: 1.0 },
  { source: "math_basics", target: "statistics", weight: 0.5 },
  // Physics
  { source: "algebra_basics", target: "kinematics", weight: 0.9 },
  { source: "linear_eq", target: "kinematics", weight: 0.8 },
  { source: "physics_units", target: "kinematics", weight: 0.6 },
  { source: "kinematics", target: "newtons_laws", weight: 1.0 },
  { source: "newtons_laws", target: "work_energy", weight: 1.0 },
  { source: "calculus_intro", target: "work_energy", weight: 0.7 },
  { source: "trigonometry", target: "waves", weight: 0.9 },
  { source: "newtons_laws", target: "waves", weight: 0.8 },
  // Programming
  { source: "prog_basics", target: "variables_types", weight: 1.0 },
  { source: "variables_types", target: "control_flow", weight: 1.0 },
  { source: "control_flow", target: "functions_prog", weight: 1.0 },
  { source: "functions_prog", target: "data_structures", weight: 0.8 },
  { source: "control_flow", target: "data_structures", weight: 0.7 },
  { source: "functions_prog", target: "recursion", weight: 1.0 },
  { source: "data_structures", target: "recursion", weight: 0.6 },
  { source: "recursion", target: "algorithms", weight: 1.0 },
  { source: "data_structures", target: "algorithms", weight: 0.8 },
];

export const domainSummaries: DomainSummary[] = [
  { domain: "Mathematics", weaknessCount: 8, avgSeverity: 0.690, topWeakness: "Linear Equations", trend: "declining" },
  { domain: "Physics", weaknessCount: 4, avgSeverity: 0.647, topWeakness: "Kinematics", trend: "declining" },
  { domain: "Programming", weaknessCount: 5, avgSeverity: 0.661, topWeakness: "Control Flow", trend: "declining" },
];

export const interventionSteps: InterventionStep[] = [
  { id: "1", topic_id: "algebra_basics", topic_name: "Algebra Basics", domain: "Mathematics", estimatedMinutes: 90, priority: 1, dependencies: [], masteryTarget: 0.7, currentMastery: 0.095 },
  { id: "2", topic_id: "control_flow", topic_name: "Control Flow", domain: "Programming", estimatedMinutes: 75, priority: 2, dependencies: [], masteryTarget: 0.7, currentMastery: 0.133 },
  { id: "3", topic_id: "linear_eq", topic_name: "Linear Equations", domain: "Mathematics", estimatedMinutes: 60, priority: 3, dependencies: ["algebra_basics"], masteryTarget: 0.7, currentMastery: 0.095 },
  { id: "4", topic_id: "functions_prog", topic_name: "Functions & Scope", domain: "Programming", estimatedMinutes: 60, priority: 4, dependencies: ["control_flow"], masteryTarget: 0.7, currentMastery: 0.132 },
  { id: "5", topic_id: "functions", topic_name: "Functions & Graphs", domain: "Mathematics", estimatedMinutes: 45, priority: 5, dependencies: ["linear_eq"], masteryTarget: 0.65, currentMastery: 0.095 },
  { id: "6", topic_id: "kinematics", topic_name: "Kinematics", domain: "Physics", estimatedMinutes: 60, priority: 6, dependencies: ["algebra_basics", "linear_eq"], masteryTarget: 0.65, currentMastery: 0.086 },
  { id: "7", topic_id: "data_structures", topic_name: "Data Structures", domain: "Programming", estimatedMinutes: 75, priority: 7, dependencies: ["functions_prog", "control_flow"], masteryTarget: 0.65, currentMastery: 0.133 },
  { id: "8", topic_id: "probability", topic_name: "Probability", domain: "Mathematics", estimatedMinutes: 45, priority: 8, dependencies: ["algebra_basics"], masteryTarget: 0.6, currentMastery: 0.097 },
];
